// City panel: for each city, the rendered share against the authored share of the region it
// actually sits in, at a zoom where that region is the finest thing on screen. One number
// (total absolute error, in percentage points) to tune point density against.
export const PANEL = [
  // city,            lon,     lat,   zoom, dataset, region it belongs to
  ['Rome',            12.5,   41.9,  6, 'chr', 'Italy'],
  ['Lyon',             4.84,  45.76, 6, 'chr', 'France'],
  ['Munich',          11.58,  48.14, 6, 'chr', 'Central Europe'],
  ['Warsaw',          21.0,   52.2,  6, 'chr', 'Poland & Baltics'],
  ['Madrid',          -3.7,   40.4,  6, 'chr', 'Iberia'],
  ['Glasgow',         -4.25,  55.86, 6, 'chr', 'Britain & Ireland'],
  ['Athens',          23.7,   38.0,  6, 'chr', 'Greece & Balkans'],
  ['Stockholm',       18.1,   59.3,  6, 'chr', 'Scandinavia'],
  ['Moscow',          37.6,   55.8,  6, 'chr', 'Rus & Russia'],
  ['Istanbul',        29.0,   41.0,  6, 'isl', 'Anatolia'],
  ['Cairo',           31.2,   30.0,  6, 'isl', 'Egypt'],
  ['Tunis',           10.3,   36.8,  6, 'isl', 'Maghreb'],
  ['Baghdad',         44.4,   33.3,  6, 'isl', 'Mesopotamia'],
  ['Tehran',          51.4,   35.7,  6, 'isl', 'Persia'],
  ['Riyadh',          46.7,   24.7,  6, 'isl', 'Arabia'],
  ['Tashkent',        69.2,   41.3,  6, 'isl', 'Central Asia'],
  ['Delhi',           77.2,   28.6,  6, 'isl', 'India'],
  ['Jakarta',        106.8,   -6.2,  6, 'isl', 'Maritime Southeast Asia'],
  ['Lagos',            3.4,    6.5,  6, 'isl', 'West Africa'],
  ['Addis Ababa',     38.7,    9.0,  6, 'chr', 'Ethiopia & Horn'],
  ['Beijing',        116.4,   39.9,  6, 'bud', 'China'],
  ['Tokyo',          139.7,   35.7,  6, 'bud', 'Korea & Japan'],
  ['Bangkok',        100.5,   13.8,  6, 'bud', 'Mainland Southeast Asia'],
  ['Colombo',         79.9,    6.9,  6, 'bud', 'Sri Lanka'],
  ['Lhasa',           91.1,   29.7,  6, 'bud', 'Tibet & Bhutan'],
  ['Ulaanbaatar',    106.9,   47.9,  6, 'bud', 'Mongolia'],
  ['Kathmandu',       85.3,   27.7,  6, 'bud', 'Nepal'],
  ['Manila',         121.0,   14.6,  6, 'chr', 'Philippines'],
  ['Denver',        -105.0,   39.7,  6, 'chr', 'North America'],
  ['Mexico City',    -99.1,   19.4,  6, 'chr', 'Mesoamerica & Caribbean'],
  ['Sao Paulo',      -46.6,  -23.5,  6, 'chr', 'South America'],
  ['Sydney',         151.2,  -33.9,  6, 'chr', 'Oceania'],
  ['Kinshasa',        15.3,   -4.3,  6, 'chr', 'Central Africa'],
  ['Nairobi',         36.8,   -1.3,  6, 'chr', 'East Africa'],
  ['Johannesburg',    28.0,  -26.2,  6, 'chr', 'Southern Africa'],
  ['Dearborn',       -83.18,  42.32,60, 'isl', 'Dearborn (city)'],
];
